import { useEffect, useState } from 'react'
import { fetchFullTextStatus, fetchHighlightedPdf, type FullTextStatus, type AttributionAnswerSentence, type AttributionSourceSentence, type HighlightedPdf } from '../lib/api'

export interface DocumentDetail {
  id?: string | null
  pmid?: string | null
  title: string
  source: string
  text?: string | null
  snippet: string
  kind: 'trusted' | 'blocked' | 'reinstated' | 'retained'
  rank?: number
  category?: string
  harmful_probability?: number | null
  relevance_score?: number | null
  retrieval_score?: number | null
  block_reason?: string | null
  scorer?: string | null
  verification_status?: string
  /** Abstract split into sentences, with links to the answer sentences each one supports */
  sentences?: AttributionSourceSentence[]
  /** Answer sentence to emphasise (set when the user clicked a citation in the answer) */
  focusAnswerSentence?: number
}

interface Props {
  doc: DocumentDetail | null
  tau?: number
  answerSentences?: AttributionAnswerSentence[]
  onClose: () => void
}

const KIND_STYLE: Record<DocumentDetail['kind'], { label: string; className: string }> = {
  trusted: {
    label: '✓ Sent to the generator (Top-5)',
    className: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300 border-emerald-500/30',
  },
  retained: {
    label: '✓ Retained by the safety filter',
    className: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300 border-emerald-500/30',
  },
  blocked: {
    label: '✕ Blocked by the safety filter',
    className: 'bg-red-600 text-white border-red-600',
  },
  reinstated: {
    label: '↺ Reinstated by the fallback guard',
    className: 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300 border-amber-500/30',
  },
}

function pubmedId(doc: DocumentDetail): string | null {
  // Only PubMedQA documents (ids "pqa_<pmid>") carry real PMIDs. The hand-written demo
  // corpus (backend/data/sample_corpus.json) has placeholder PMIDs that point at unrelated papers.
  const match = doc.id ? /^pqa_(\d{5,9})$/.exec(String(doc.id)) : null
  return match ? match[1] : null
}

function escapeHtml(text: string): string {
  return text.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!)
}

/** Opens a print view of the highlighted document so it can be saved as a PDF. */
function printDocument(doc: DocumentDetail, answerSentences: AttributionAnswerSentence[], pmid: string | null) {
  const win = window.open('', '_blank')
  if (!win) return
  const body = (doc.sentences && doc.sentences.length > 0
    ? doc.sentences.map((s) =>
        s.answer_sentences.length > 0
          ? `<mark>${escapeHtml(s.text)}</mark><sup>${s.answer_sentences.map((i) => `A${i + 1}`).join(',')}</sup>`
          : escapeHtml(s.text),
      ).join(' ')
    : escapeHtml(doc.text || doc.snippet))
  const used = (doc.sentences ?? [])
    .flatMap((s) => s.answer_sentences)
    .filter((v, i, a) => a.indexOf(v) === i)
    .sort((a, b) => a - b)
    .map((i) => `<li><b>A${i + 1}.</b> ${escapeHtml(answerSentences[i]?.text ?? '')}</li>`)
    .join('')
  win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(doc.title)}</title>
<style>body{font-family:Georgia,serif;max-width:720px;margin:32px auto;line-height:1.6;color:#111}
h1{font-size:20px}.meta{font:12px monospace;color:#555}mark{background:#fde68a}sup{font:10px monospace;color:#92400e}
li{margin:4px 0}.note{font:11px sans-serif;color:#555;border-top:1px solid #ddd;margin-top:24px;padding-top:8px}</style></head><body>
<h1>${doc.rank !== undefined ? `[${doc.rank}] ` : ''}${escapeHtml(doc.title)}</h1>
<div class="meta">${escapeHtml(doc.source)}${doc.id ? ` · ${escapeHtml(String(doc.id))}` : ''}${pmid ? ` · PMID ${pmid}` : ''}</div>
<h3>Abstract (highlighted where it supports the answer)</h3><p>${body}</p>
${used ? `<h3>Answer sentences supported by this document</h3><ol style="list-style:none;padding:0">${used}</ol>` : ''}
<p class="note">Generated by SafeMed AI. Highlights are computed by sentence similarity between the answer and this document.</p>
<script>window.onload=()=>window.print()</script></body></html>`)
  win.document.close()
}

export default function DocumentDetailModal({ doc, tau = 0.5, answerSentences = [], onClose }: Props) {
  const [pdfState, setPdfState] = useState<{ loading: boolean; error?: string; pdf?: HighlightedPdf }>({ loading: false })

  const [articlePdf, setArticlePdf] = useState<{ checking: boolean; status?: FullTextStatus; error?: string }>({ checking: false })

  useEffect(() => {
    setPdfState({ loading: false })
    setArticlePdf({ checking: false })
    const pmid = doc ? pubmedId(doc) : null
    if (!pmid) return
    let alive = true
    setArticlePdf({ checking: true })
    fetchFullTextStatus(pmid)
      .then((status) => alive && setArticlePdf({ checking: false, status, error: status.error ?? undefined }))
      .catch((err) => alive && setArticlePdf({ checking: false, error: err.message }))
    return () => {
      alive = false
    }
  }, [doc?.id])

  const openSourcePdf = async (current: DocumentDetail, pmid: string) => {
    const used = (current.sentences ?? []).filter((s) => s.answer_sentences.length > 0)
    setPdfState({ loading: true })
    try {
      const pdf = await fetchHighlightedPdf(
        pmid,
        used.map((s) => s.text),
        used.map((s) => `Supports answer sentence ${s.answer_sentences.map((i) => i + 1).join(', ')}`),
      )
      setPdfState({ loading: false, pdf })
      window.open(`${pdf.url}#page=${pdf.firstPage}`, '_blank', 'noopener')
    } catch (err: any) {
      setPdfState({ loading: false, error: err.message || 'Could not load the source PDF.' })
    }
  }
  useEffect(() => {
    if (!doc) return
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && onClose()
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [doc, onClose])

  if (!doc) return null

  const style = KIND_STYLE[doc.kind]
  const pmid = pubmedId(doc)
  const fullText = doc.text || doc.snippet
  const pHD = doc.harmful_probability
  const isDemoDoc = !pmid && !!doc.id && !String(doc.id).startsWith('pqa_')
  const usedIn = (doc.sentences ?? [])
    .flatMap((s) => s.answer_sentences)
    .filter((v, i, a) => a.indexOf(v) === i)
    .sort((a, b) => a - b)

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-label={doc.title}
    >
      <div
        className="w-full max-w-2xl max-h-[85vh] overflow-y-auto rounded-2xl border border-border bg-card shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="sticky top-0 bg-card border-b border-border p-4 flex items-start justify-between gap-3">
          <div className="space-y-1.5">
            <span className={`inline-block px-2 py-0.5 rounded text-[10px] font-mono font-bold border ${style.className}`}>
              {style.label}
            </span>
            <h3 className="text-sm font-semibold text-foreground leading-snug">
              {doc.rank !== undefined && <span className="font-mono text-muted-foreground mr-1.5">[{doc.rank}]</span>}
              {doc.title}
            </h3>
            <p className="text-[11px] font-mono text-muted-foreground">
              {doc.source}
              {doc.id && <> • {doc.id}</>}
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-muted-foreground hover:text-foreground text-lg leading-none px-2 cursor-pointer"
            aria-label="Close"
          >
            ✕
          </button>
        </div>

        <div className="p-4 space-y-4 text-xs">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 font-mono">
            {pHD !== undefined && pHD !== null && (
              <div className="rounded-lg border border-border p-2">
                <div className="text-[10px] text-muted-foreground">P(HD)</div>
                <div className={`font-bold ${pHD >= tau ? 'text-red-600 dark:text-red-400' : 'text-foreground'}`}>
                  {pHD.toFixed(4)}
                </div>
                <div className="text-[10px] text-muted-foreground">τ = {tau.toFixed(2)}</div>
              </div>
            )}
            {doc.category && (
              <div className="rounded-lg border border-border p-2">
                <div className="text-[10px] text-muted-foreground">Category</div>
                <div className="font-bold text-foreground">{doc.category}</div>
              </div>
            )}
            {doc.relevance_score !== undefined && doc.relevance_score !== null && (
              <div className="rounded-lg border border-border p-2">
                <div className="text-[10px] text-muted-foreground">Rerank score</div>
                <div className="font-bold text-foreground">{doc.relevance_score.toFixed(4)}</div>
              </div>
            )}
            {doc.retrieval_score !== undefined && doc.retrieval_score !== null && (
              <div className="rounded-lg border border-border p-2">
                <div className="text-[10px] text-muted-foreground">Retrieval score</div>
                <div className="font-bold text-foreground">{doc.retrieval_score.toFixed(4)}</div>
              </div>
            )}
          </div>

          {doc.block_reason && (
            <p className="text-red-700 dark:text-red-300 text-[11px] bg-red-100/60 dark:bg-red-950/50 p-2.5 rounded-lg border border-red-500/20">
              <strong>Filter reason:</strong> {doc.block_reason}
              {doc.scorer && <span className="font-mono text-muted-foreground"> ({doc.scorer})</span>}
            </p>
          )}

          <div className="space-y-1">
            <div className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">
              {doc.text ? 'Full abstract' : 'Excerpt'}
            </div>
            <p className="text-sm text-foreground/90 font-serif leading-relaxed bg-background/60 p-3 rounded-lg border border-border/50">
              {doc.sentences && doc.sentences.length > 0
                ? doc.sentences.map((s, idx) => {
                    const used = s.answer_sentences.length > 0
                    const focused = doc.focusAnswerSentence !== undefined && s.answer_sentences.includes(doc.focusAnswerSentence)
                    return (
                      <span key={idx}>
                        {used ? (
                          <mark
                            title={s.answer_sentences
                              .map((i) => `Supports answer sentence ${i + 1}: ${answerSentences[i]?.text ?? ''}`)
                              .join('\n')}
                            className={`rounded px-0.5 text-foreground ${
                              focused ? 'bg-amber-300/90 dark:bg-amber-500/60 ring-2 ring-amber-500' : 'bg-amber-200/70 dark:bg-amber-500/30'
                            }`}
                          >
                            {s.text}
                            <sup className="ml-0.5 font-mono text-[9px] text-amber-700 dark:text-amber-300">
                              {s.answer_sentences.map((i) => `A${i + 1}`).join(',')}
                            </sup>
                          </mark>
                        ) : (
                          s.text
                        )}{' '}
                      </span>
                    )
                  })
                : fullText}
            </p>
          </div>

          {usedIn.length > 0 && (
            <div className="space-y-1.5">
              <div className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">
                Where this document was used in the answer
              </div>
              <ul className="space-y-1">
                {usedIn.map((i) => (
                  <li
                    key={i}
                    className={`text-xs p-2 rounded-lg border ${
                      i === doc.focusAnswerSentence ? 'border-amber-500/60 bg-amber-50/40 dark:bg-amber-950/30' : 'border-border/50'
                    }`}
                  >
                    <span className="font-mono font-bold text-amber-700 dark:text-amber-300 mr-1.5">A{i + 1}</span>
                    {answerSentences[i]?.text}
                  </li>
                ))}
              </ul>
              <p className="text-[10px] text-muted-foreground">
                Highlights are matched by sentence similarity between the answer and this abstract.
              </p>
            </div>
          )}
          {doc.sentences && usedIn.length === 0 && doc.kind === 'trusted' && (
            <p className="text-[11px] text-muted-foreground italic">
              No sentence of this document closely matches the answer, so it was given to the generator but not visibly used.
            </p>
          )}

          <div className="flex flex-wrap items-center gap-4">
          {pmid && (
            <button
              type="button"
              disabled={pdfState.loading || articlePdf.checking || (articlePdf.status?.has_pdf === false && !articlePdf.error)}
              onClick={() => openSourcePdf(doc, pmid)}
              className="inline-flex items-center gap-1.5 text-xs font-mono font-semibold px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white disabled:bg-muted disabled:text-muted-foreground disabled:cursor-not-allowed cursor-pointer"
            >
              {articlePdf.checking
                ? 'Checking PubMed Central for the full article...'
                : articlePdf.status?.has_pdf === false && !articlePdf.error
                  ? 'No open-access PDF for this article'
                  : pdfState.loading
                    ? 'Highlighting the full article...'
                    : `📄 Open full article PDF (highlighted)${articlePdf.status?.pmcid ? ` · ${articlePdf.status.pmcid}` : ''}`}
            </button>
          )}
          <button
            type="button"
            onClick={() => printDocument(doc, answerSentences, pmid)}
            className="inline-flex items-center gap-1.5 text-xs font-mono font-semibold px-3 py-1.5 rounded-lg border border-border hover:bg-muted cursor-pointer"
          >
            ⤓ Save highlighted copy as PDF
          </button>
          {pmid && (
            <a
              href={`https://pubmed.ncbi.nlm.nih.gov/${pmid}/`}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-mono font-semibold text-emerald-600 dark:text-emerald-400 hover:underline"
            >
              Open PMID {pmid} on PubMed ↗
            </a>
          )}
          </div>
          {pdfState.pdf && (
            <p className="text-[11px] font-mono text-muted-foreground">
              Highlighted {pdfState.pdf.found} of {pdfState.pdf.requested} cited sentences in the article PDF.{' '}
              <a href={`${pdfState.pdf.url}#page=${pdfState.pdf.firstPage}`} target="_blank" rel="noopener noreferrer" className="underline">
                Open again
              </a>
              {' · '}
              <a href={pdfState.pdf.url} download={`PMID${pmid}_highlighted.pdf`} className="underline">
                Download
              </a>
            </p>
          )}
          {articlePdf.status?.has_pdf === false && !articlePdf.error && (
            <p className="text-[11px] text-muted-foreground">
              {articlePdf.status.pmcid
                ? `This article is in PubMed Central (${articlePdf.status.pmcid}) but is not open access, so its PDF can't be downloaded.`
                : 'This article is not in PubMed Central, so only its abstract is available (highlighted above). Most PubMed articles are like this.'}
            </p>
          )}
          {articlePdf.error && (
            <p className="text-[11px] text-amber-700 dark:text-amber-300">
              Couldn't check for the full article: {articlePdf.error}
            </p>
          )}
          {pdfState.error && (
            <p className="text-[11px] text-amber-700 dark:text-amber-300">
              {pdfState.error} The highlighted abstract above is shown instead.
            </p>
          )}
          {isDemoDoc && String(doc.id).startsWith('hd_') && (
            <p className="text-[10px] text-red-700 dark:text-red-300">
              Synthetic harmful document generated for filter testing (backend/scripts/generate_harmful_docs.py). It is not
              a real study and has no PubMed record.
            </p>
          )}
          {isDemoDoc && !String(doc.id).startsWith('hd_') && (
            <p className="text-[10px] text-muted-foreground">
              This document comes from the illustrative sample corpus written for the original demo cases, so it has no
              verified PubMed record. The default demo corpus (<code className="font-mono">SAFEMED_CORPUS=demo</code>) uses
              real PubMedQA abstracts that link to PubMed.
            </p>
          )}
        </div>
      </div>
    </div>
  )
}
